name: Daily Automation

on:
  schedule:
    - cron: '0 3 * * *' 
  push:  # Triggers on any push to the repository
  workflow_dispatch:
  
jobs:
  run-script:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  

      - name: Set up Python
        uses: actions/setup-python@v4 
        with:
          python-version: '3.x'  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrades pip
          pip install -r requirements.txt  


      - name: Run script
        run: python email-automation.py
        env:
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
          TG_CHAT_TOKEN: ${{ secrets.TG_CHAT_TOKEN }}
